
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jul 10 00:42:53 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 48;
  public static final int CONST = 17;
  public static final int PERIOD = 41;
  public static final int NAMESP = 24;
  public static final int FOLLOW = 44;
  public static final int LPAREN = 6;
  public static final int GREATER = 31;
  public static final int SEMI = 5;
  public static final int CONTINUE = 21;
  public static final int LESS = 33;
  public static final int FOR = 22;
  public static final int MINUS = 25;
  public static final int GREQ = 32;
  public static final int STATIC = 23;
  public static final int RPAREN = 7;
  public static final int AND = 35;
  public static final int OR = 36;
  public static final int BOOL = 45;
  public static final int COMMA = 8;
  public static final int CLASS = 16;
  public static final int LSQBRACK = 42;
  public static final int INC = 37;
  public static final int DIV = 27;
  public static final int EXT = 20;
  public static final int EOL = 40;
  public static final int PLUS = 11;
  public static final int IF = 49;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int NUMBER = 46;
  public static final int MOD = 28;
  public static final int NEQ = 30;
  public static final int IDENT = 47;
  public static final int BREAK = 15;
  public static final int VOID = 13;
  public static final int EQ = 29;
  public static final int COLON = 39;
  public static final int ELSE = 50;
  public static final int LBRACE = 3;
  public static final int READ = 19;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int RSQBRACK = 43;
  public static final int LEQ = 34;
  public static final int DEC = 38;
  public static final int RANG = 14;
  public static final int PRINT = 9;
}

